import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "12px 16px",
          borderBottom: "1px solid #e5e7eb"
        }}>
          <a href="/" style={{ textDecoration: "none", fontWeight: 600 }}>Home</a>
          <nav style={{ display: "flex", gap: 12 }}>
            <a
              href="/bva"
              style={{
                textDecoration: "none",
                padding: "6px 10px",
                border: "1px solid #e5e7eb",
                borderRadius: 6,
                fontSize: 13,
                color: "inherit",
              }}
            >
              BvA Test
            </a>
          </nav>
        </header>
        <div style={{ padding: 16 }}>
          {children}
        </div>
      </body>
    </html>
  );
}
